apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-admin-consulta-medica
subjects:
  - kind: ServiceAccount
    name: default
    namespace: consulta-medica
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin