apiVersion: v1
data:
  DB_PASSWORD: VHVDb250cmFzZcOxYVNlZ3VyYQ==
  MYSQL_PASSWORD: VHVDb250cmFzZcOxYVNlZ3VyYQ==
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
kind: Secret
metadata:
  creationTimestamp: "2026-02-16T22:41:22Z"
  name: db-secret
  namespace: consulta-medica
  resourceVersion: "1050"
  uid: 732b7e20-9cd2-4774-8ccb-903184a8810c
type: Opaque
